// function simplefunction.test 2
(simplefunction.test)
@0                                                                  // 0
D=A                                                                 // 1
@SP                                                                 // 2
A=M                                                                 // 3
M=D                                                                 // 4
@SP                                                                 // 5
M=M+1                                                               // 6
@0                                                                  // 7
D=A                                                                 // 8
@SP                                                                 // 9
A=M                                                                 // 10
M=D                                                                 // 11
@SP                                                                 // 12
M=M+1                                                               // 13
// push local 0
@0                                                                  // 14
D=A                                                                 // 15
@LCL                                                                // 16
A=D+M                                                               // 17
D=M                                                                 // 18
@SP                                                                 // 19
A=M                                                                 // 20
M=D                                                                 // 21
@SP                                                                 // 22
M=M+1                                                               // 23
// push local 1
@1                                                                  // 24
D=A                                                                 // 25
@LCL                                                                // 26
A=D+M                                                               // 27
D=M                                                                 // 28
@SP                                                                 // 29
A=M                                                                 // 30
M=D                                                                 // 31
@SP                                                                 // 32
M=M+1                                                               // 33
// add
@SP                                                                 // 34
M=M-1                                                               // 35
@SP                                                                 // 36
A=M                                                                 // 37
D=M                                                                 // 38
@SP                                                                 // 39
M=M-1                                                               // 40
@SP                                                                 // 41
A=M                                                                 // 42
M=M+D                                                               // 43
@SP                                                                 // 44
M=M+1                                                               // 45
// not
@SP                                                                 // 46
M=M-1                                                               // 47
@SP                                                                 // 48
A=M                                                                 // 49
M=!M                                                                // 50
@SP                                                                 // 51
M=M+1                                                               // 52
// push argument 0
@0                                                                  // 53
D=A                                                                 // 54
@ARG                                                                // 55
A=D+M                                                               // 56
D=M                                                                 // 57
@SP                                                                 // 58
A=M                                                                 // 59
M=D                                                                 // 60
@SP                                                                 // 61
M=M+1                                                               // 62
// add
@SP                                                                 // 63
M=M-1                                                               // 64
@SP                                                                 // 65
A=M                                                                 // 66
D=M                                                                 // 67
@SP                                                                 // 68
M=M-1                                                               // 69
@SP                                                                 // 70
A=M                                                                 // 71
M=M+D                                                               // 72
@SP                                                                 // 73
M=M+1                                                               // 74
// push argument 1
@1                                                                  // 75
D=A                                                                 // 76
@ARG                                                                // 77
A=D+M                                                               // 78
D=M                                                                 // 79
@SP                                                                 // 80
A=M                                                                 // 81
M=D                                                                 // 82
@SP                                                                 // 83
M=M+1                                                               // 84
// sub
@SP                                                                 // 85
M=M-1                                                               // 86
@SP                                                                 // 87
A=M                                                                 // 88
D=M                                                                 // 89
@SP                                                                 // 90
M=M-1                                                               // 91
@SP                                                                 // 92
A=M                                                                 // 93
M=M-D                                                               // 94
@SP                                                                 // 95
M=M+1                                                               // 96
// return
@5                                                                  // 97
D=A                                                                 // 98
@LCL                                                                // 99
D=M-D                                                               // 100
A=D                                                                 // 101
D=M                                                                 // 102
@R14                                                                // 103
M=D                                                                 // 104
@0                                                                  // 105
D=A                                                                 // 106
@ARG                                                                // 107
A=D+M                                                               // 108
D=A                                                                 // 109
@R13                                                                // 110
M=D                                                                 // 111
@SP                                                                 // 112
M=M-1                                                               // 113
A=M                                                                 // 114
D=M                                                                 // 115
@R13                                                                // 116
A=M                                                                 // 117
M=D                                                                 // 118
@ARG                                                                // 119
D=M+1                                                               // 120
@SP                                                                 // 121
M=D                                                                 // 122
@LCL                                                                // 123
M=M-1                                                               // 124
@LCL                                                                // 125
A=M                                                                 // 126
D=M                                                                 // 127
@THAT                                                               // 128
M=D                                                                 // 129
@LCL                                                                // 130
M=M-1                                                               // 131
@LCL                                                                // 132
A=M                                                                 // 133
D=M                                                                 // 134
@THIS                                                               // 135
M=D                                                                 // 136
@LCL                                                                // 137
M=M-1                                                               // 138
@LCL                                                                // 139
A=M                                                                 // 140
D=M                                                                 // 141
@ARG                                                                // 142
M=D                                                                 // 143
@LCL                                                                // 144
M=M-1                                                               // 145
@LCL                                                                // 146
A=M                                                                 // 147
D=M                                                                 // 148
@LCL                                                                // 149
M=D                                                                 // 150
@R14                                                                // 151
A=M                                                                 // 152
0;JMP                                                               // 153
