// this is the bootstrap code block
@256                                    // 0
D=A                                     // 1
@SP                                     // 2
M=D                                     // 3
@sys.init.return_0                      // 4
D=A                                     // 5
@SP                                     // 6
A=M                                     // 7
M=D                                     // 8
@SP                                     // 9
M=M+1                                   // 10
@LCL                                    // 11
D=M                                     // 12
@SP                                     // 13
A=M                                     // 14
M=D                                     // 15
@SP                                     // 16
M=M+1                                   // 17
@ARG                                    // 18
D=M                                     // 19
@SP                                     // 20
A=M                                     // 21
M=D                                     // 22
@SP                                     // 23
M=M+1                                   // 24
@THIS                                   // 25
D=M                                     // 26
@SP                                     // 27
A=M                                     // 28
M=D                                     // 29
@SP                                     // 30
M=M+1                                   // 31
@THAT                                   // 32
D=M                                     // 33
@SP                                     // 34
A=M                                     // 35
M=D                                     // 36
@SP                                     // 37
M=M+1                                   // 38
@SP                                     // 39
D=M                                     // 40
@5                                      // 41
D=D-A                                   // 42
@0                                      // 43
D=D-A                                   // 44
@ARG                                    // 45
M=D                                     // 46
@SP                                     // 47
D=M                                     // 48
@LCL                                    // 49
M=D                                     // 50
@sys.init                               // 51
0;JMP                                   // 52
(sys.init.return_0)
// function sys.init 0
(sys.init)
// push constant 4000
@4000                                   // 53
D=A                                     // 54
@SP                                     // 55
A=M                                     // 56
M=D                                     // 57
@SP                                     // 58
M=M+1                                   // 59
// pop pointer 0
@THIS                                   // 60
D=A                                     // 61
@R13                                    // 62
M=D                                     // 63
@SP                                     // 64
M=M-1                                   // 65
A=M                                     // 66
D=M                                     // 67
@R13                                    // 68
A=M                                     // 69
M=D                                     // 70
// push constant 5000
@5000                                   // 71
D=A                                     // 72
@SP                                     // 73
A=M                                     // 74
M=D                                     // 75
@SP                                     // 76
M=M+1                                   // 77
// pop pointer 1
@THAT                                   // 78
D=A                                     // 79
@R13                                    // 80
M=D                                     // 81
@SP                                     // 82
M=M-1                                   // 83
A=M                                     // 84
D=M                                     // 85
@R13                                    // 86
A=M                                     // 87
M=D                                     // 88
// call sys.main 0
@sys.main.return_1                      // 89
D=A                                     // 90
@SP                                     // 91
A=M                                     // 92
M=D                                     // 93
@SP                                     // 94
M=M+1                                   // 95
@LCL                                    // 96
D=M                                     // 97
@SP                                     // 98
A=M                                     // 99
M=D                                     // 100
@SP                                     // 101
M=M+1                                   // 102
@ARG                                    // 103
D=M                                     // 104
@SP                                     // 105
A=M                                     // 106
M=D                                     // 107
@SP                                     // 108
M=M+1                                   // 109
@THIS                                   // 110
D=M                                     // 111
@SP                                     // 112
A=M                                     // 113
M=D                                     // 114
@SP                                     // 115
M=M+1                                   // 116
@THAT                                   // 117
D=M                                     // 118
@SP                                     // 119
A=M                                     // 120
M=D                                     // 121
@SP                                     // 122
M=M+1                                   // 123
@SP                                     // 124
D=M                                     // 125
@5                                      // 126
D=D-A                                   // 127
@0                                      // 128
D=D-A                                   // 129
@ARG                                    // 130
M=D                                     // 131
@SP                                     // 132
D=M                                     // 133
@LCL                                    // 134
M=D                                     // 135
@sys.main                               // 136
0;JMP                                   // 137
(sys.main.return_1)
// pop temp 1
@6                                      // 138
D=A                                     // 139
@R13                                    // 140
M=D                                     // 141
@SP                                     // 142
M=M-1                                   // 143
A=M                                     // 144
D=M                                     // 145
@R13                                    // 146
A=M                                     // 147
M=D                                     // 148
// label loop
(loop)
// goto loop
@loop                                   // 149
0;JMP                                   // 150
// function sys.main 5
(sys.main)
@0                                      // 151
D=A                                     // 152
@SP                                     // 153
A=M                                     // 154
M=D                                     // 155
@SP                                     // 156
M=M+1                                   // 157
@0                                      // 158
D=A                                     // 159
@SP                                     // 160
A=M                                     // 161
M=D                                     // 162
@SP                                     // 163
M=M+1                                   // 164
@0                                      // 165
D=A                                     // 166
@SP                                     // 167
A=M                                     // 168
M=D                                     // 169
@SP                                     // 170
M=M+1                                   // 171
@0                                      // 172
D=A                                     // 173
@SP                                     // 174
A=M                                     // 175
M=D                                     // 176
@SP                                     // 177
M=M+1                                   // 178
@0                                      // 179
D=A                                     // 180
@SP                                     // 181
A=M                                     // 182
M=D                                     // 183
@SP                                     // 184
M=M+1                                   // 185
// push constant 4001
@4001                                   // 186
D=A                                     // 187
@SP                                     // 188
A=M                                     // 189
M=D                                     // 190
@SP                                     // 191
M=M+1                                   // 192
// pop pointer 0
@THIS                                   // 193
D=A                                     // 194
@R13                                    // 195
M=D                                     // 196
@SP                                     // 197
M=M-1                                   // 198
A=M                                     // 199
D=M                                     // 200
@R13                                    // 201
A=M                                     // 202
M=D                                     // 203
// push constant 5001
@5001                                   // 204
D=A                                     // 205
@SP                                     // 206
A=M                                     // 207
M=D                                     // 208
@SP                                     // 209
M=M+1                                   // 210
// pop pointer 1
@THAT                                   // 211
D=A                                     // 212
@R13                                    // 213
M=D                                     // 214
@SP                                     // 215
M=M-1                                   // 216
A=M                                     // 217
D=M                                     // 218
@R13                                    // 219
A=M                                     // 220
M=D                                     // 221
// push constant 200
@200                                    // 222
D=A                                     // 223
@SP                                     // 224
A=M                                     // 225
M=D                                     // 226
@SP                                     // 227
M=M+1                                   // 228
// pop local 1
@1                                      // 229
D=A                                     // 230
@LCL                                    // 231
A=D+M                                   // 232
D=A                                     // 233
@R13                                    // 234
M=D                                     // 235
@SP                                     // 236
M=M-1                                   // 237
A=M                                     // 238
D=M                                     // 239
@R13                                    // 240
A=M                                     // 241
M=D                                     // 242
// push constant 40
@40                                     // 243
D=A                                     // 244
@SP                                     // 245
A=M                                     // 246
M=D                                     // 247
@SP                                     // 248
M=M+1                                   // 249
// pop local 2
@2                                      // 250
D=A                                     // 251
@LCL                                    // 252
A=D+M                                   // 253
D=A                                     // 254
@R13                                    // 255
M=D                                     // 256
@SP                                     // 257
M=M-1                                   // 258
A=M                                     // 259
D=M                                     // 260
@R13                                    // 261
A=M                                     // 262
M=D                                     // 263
// push constant 6
@6                                      // 264
D=A                                     // 265
@SP                                     // 266
A=M                                     // 267
M=D                                     // 268
@SP                                     // 269
M=M+1                                   // 270
// pop local 3
@3                                      // 271
D=A                                     // 272
@LCL                                    // 273
A=D+M                                   // 274
D=A                                     // 275
@R13                                    // 276
M=D                                     // 277
@SP                                     // 278
M=M-1                                   // 279
A=M                                     // 280
D=M                                     // 281
@R13                                    // 282
A=M                                     // 283
M=D                                     // 284
// push constant 123
@123                                    // 285
D=A                                     // 286
@SP                                     // 287
A=M                                     // 288
M=D                                     // 289
@SP                                     // 290
M=M+1                                   // 291
// call sys.add12 1
@sys.add12.return_2                     // 292
D=A                                     // 293
@SP                                     // 294
A=M                                     // 295
M=D                                     // 296
@SP                                     // 297
M=M+1                                   // 298
@LCL                                    // 299
D=M                                     // 300
@SP                                     // 301
A=M                                     // 302
M=D                                     // 303
@SP                                     // 304
M=M+1                                   // 305
@ARG                                    // 306
D=M                                     // 307
@SP                                     // 308
A=M                                     // 309
M=D                                     // 310
@SP                                     // 311
M=M+1                                   // 312
@THIS                                   // 313
D=M                                     // 314
@SP                                     // 315
A=M                                     // 316
M=D                                     // 317
@SP                                     // 318
M=M+1                                   // 319
@THAT                                   // 320
D=M                                     // 321
@SP                                     // 322
A=M                                     // 323
M=D                                     // 324
@SP                                     // 325
M=M+1                                   // 326
@SP                                     // 327
D=M                                     // 328
@5                                      // 329
D=D-A                                   // 330
@1                                      // 331
D=D-A                                   // 332
@ARG                                    // 333
M=D                                     // 334
@SP                                     // 335
D=M                                     // 336
@LCL                                    // 337
M=D                                     // 338
@sys.add12                              // 339
0;JMP                                   // 340
(sys.add12.return_2)
// pop temp 0
@5                                      // 341
D=A                                     // 342
@R13                                    // 343
M=D                                     // 344
@SP                                     // 345
M=M-1                                   // 346
A=M                                     // 347
D=M                                     // 348
@R13                                    // 349
A=M                                     // 350
M=D                                     // 351
// push local 0
@0                                      // 352
D=A                                     // 353
@LCL                                    // 354
A=D+M                                   // 355
D=M                                     // 356
@SP                                     // 357
A=M                                     // 358
M=D                                     // 359
@SP                                     // 360
M=M+1                                   // 361
// push local 1
@1                                      // 362
D=A                                     // 363
@LCL                                    // 364
A=D+M                                   // 365
D=M                                     // 366
@SP                                     // 367
A=M                                     // 368
M=D                                     // 369
@SP                                     // 370
M=M+1                                   // 371
// push local 2
@2                                      // 372
D=A                                     // 373
@LCL                                    // 374
A=D+M                                   // 375
D=M                                     // 376
@SP                                     // 377
A=M                                     // 378
M=D                                     // 379
@SP                                     // 380
M=M+1                                   // 381
// push local 3
@3                                      // 382
D=A                                     // 383
@LCL                                    // 384
A=D+M                                   // 385
D=M                                     // 386
@SP                                     // 387
A=M                                     // 388
M=D                                     // 389
@SP                                     // 390
M=M+1                                   // 391
// push local 4
@4                                      // 392
D=A                                     // 393
@LCL                                    // 394
A=D+M                                   // 395
D=M                                     // 396
@SP                                     // 397
A=M                                     // 398
M=D                                     // 399
@SP                                     // 400
M=M+1                                   // 401
// add
@SP                                     // 402
M=M-1                                   // 403
@SP                                     // 404
A=M                                     // 405
D=M                                     // 406
@SP                                     // 407
M=M-1                                   // 408
@SP                                     // 409
A=M                                     // 410
M=M+D                                   // 411
@SP                                     // 412
M=M+1                                   // 413
// add
@SP                                     // 414
M=M-1                                   // 415
@SP                                     // 416
A=M                                     // 417
D=M                                     // 418
@SP                                     // 419
M=M-1                                   // 420
@SP                                     // 421
A=M                                     // 422
M=M+D                                   // 423
@SP                                     // 424
M=M+1                                   // 425
// add
@SP                                     // 426
M=M-1                                   // 427
@SP                                     // 428
A=M                                     // 429
D=M                                     // 430
@SP                                     // 431
M=M-1                                   // 432
@SP                                     // 433
A=M                                     // 434
M=M+D                                   // 435
@SP                                     // 436
M=M+1                                   // 437
// add
@SP                                     // 438
M=M-1                                   // 439
@SP                                     // 440
A=M                                     // 441
D=M                                     // 442
@SP                                     // 443
M=M-1                                   // 444
@SP                                     // 445
A=M                                     // 446
M=M+D                                   // 447
@SP                                     // 448
M=M+1                                   // 449
// return
@5                                      // 450
D=A                                     // 451
@LCL                                    // 452
D=M-D                                   // 453
A=D                                     // 454
D=M                                     // 455
@R14                                    // 456
M=D                                     // 457
@0                                      // 458
D=A                                     // 459
@ARG                                    // 460
A=D+M                                   // 461
D=A                                     // 462
@R13                                    // 463
M=D                                     // 464
@SP                                     // 465
M=M-1                                   // 466
A=M                                     // 467
D=M                                     // 468
@R13                                    // 469
A=M                                     // 470
M=D                                     // 471
@ARG                                    // 472
D=M+1                                   // 473
@SP                                     // 474
M=D                                     // 475
@LCL                                    // 476
M=M-1                                   // 477
@LCL                                    // 478
A=M                                     // 479
D=M                                     // 480
@THAT                                   // 481
M=D                                     // 482
@LCL                                    // 483
M=M-1                                   // 484
@LCL                                    // 485
A=M                                     // 486
D=M                                     // 487
@THIS                                   // 488
M=D                                     // 489
@LCL                                    // 490
M=M-1                                   // 491
@LCL                                    // 492
A=M                                     // 493
D=M                                     // 494
@ARG                                    // 495
M=D                                     // 496
@LCL                                    // 497
M=M-1                                   // 498
@LCL                                    // 499
A=M                                     // 500
D=M                                     // 501
@LCL                                    // 502
M=D                                     // 503
@R14                                    // 504
A=M                                     // 505
0;JMP                                   // 506
// function sys.add12 0
(sys.add12)
// push constant 4002
@4002                                   // 507
D=A                                     // 508
@SP                                     // 509
A=M                                     // 510
M=D                                     // 511
@SP                                     // 512
M=M+1                                   // 513
// pop pointer 0
@THIS                                   // 514
D=A                                     // 515
@R13                                    // 516
M=D                                     // 517
@SP                                     // 518
M=M-1                                   // 519
A=M                                     // 520
D=M                                     // 521
@R13                                    // 522
A=M                                     // 523
M=D                                     // 524
// push constant 5002
@5002                                   // 525
D=A                                     // 526
@SP                                     // 527
A=M                                     // 528
M=D                                     // 529
@SP                                     // 530
M=M+1                                   // 531
// pop pointer 1
@THAT                                   // 532
D=A                                     // 533
@R13                                    // 534
M=D                                     // 535
@SP                                     // 536
M=M-1                                   // 537
A=M                                     // 538
D=M                                     // 539
@R13                                    // 540
A=M                                     // 541
M=D                                     // 542
// push argument 0
@0                                      // 543
D=A                                     // 544
@ARG                                    // 545
A=D+M                                   // 546
D=M                                     // 547
@SP                                     // 548
A=M                                     // 549
M=D                                     // 550
@SP                                     // 551
M=M+1                                   // 552
// push constant 12
@12                                     // 553
D=A                                     // 554
@SP                                     // 555
A=M                                     // 556
M=D                                     // 557
@SP                                     // 558
M=M+1                                   // 559
// add
@SP                                     // 560
M=M-1                                   // 561
@SP                                     // 562
A=M                                     // 563
D=M                                     // 564
@SP                                     // 565
M=M-1                                   // 566
@SP                                     // 567
A=M                                     // 568
M=M+D                                   // 569
@SP                                     // 570
M=M+1                                   // 571
// return
@5                                      // 572
D=A                                     // 573
@LCL                                    // 574
D=M-D                                   // 575
A=D                                     // 576
D=M                                     // 577
@R14                                    // 578
M=D                                     // 579
@0                                      // 580
D=A                                     // 581
@ARG                                    // 582
A=D+M                                   // 583
D=A                                     // 584
@R13                                    // 585
M=D                                     // 586
@SP                                     // 587
M=M-1                                   // 588
A=M                                     // 589
D=M                                     // 590
@R13                                    // 591
A=M                                     // 592
M=D                                     // 593
@ARG                                    // 594
D=M+1                                   // 595
@SP                                     // 596
M=D                                     // 597
@LCL                                    // 598
M=M-1                                   // 599
@LCL                                    // 600
A=M                                     // 601
D=M                                     // 602
@THAT                                   // 603
M=D                                     // 604
@LCL                                    // 605
M=M-1                                   // 606
@LCL                                    // 607
A=M                                     // 608
D=M                                     // 609
@THIS                                   // 610
M=D                                     // 611
@LCL                                    // 612
M=M-1                                   // 613
@LCL                                    // 614
A=M                                     // 615
D=M                                     // 616
@ARG                                    // 617
M=D                                     // 618
@LCL                                    // 619
M=M-1                                   // 620
@LCL                                    // 621
A=M                                     // 622
D=M                                     // 623
@LCL                                    // 624
M=D                                     // 625
@R14                                    // 626
A=M                                     // 627
0;JMP                                   // 628
