// this is the bootstrap code block
@256                                                                // 0
D=A                                                                 // 1
@SP                                                                 // 2
M=D                                                                 // 3
// call sys.init 0
@sys.init.return_0                                                  // 4
D=A                                                                 // 5
@SP                                                                 // 6
A=M                                                                 // 7
M=D                                                                 // 8
@SP                                                                 // 9
M=M+1                                                               // 10
@LCL                                                                // 11
D=M                                                                 // 12
@SP                                                                 // 13
A=M                                                                 // 14
M=D                                                                 // 15
@SP                                                                 // 16
M=M+1                                                               // 17
@ARG                                                                // 18
D=M                                                                 // 19
@SP                                                                 // 20
A=M                                                                 // 21
M=D                                                                 // 22
@SP                                                                 // 23
M=M+1                                                               // 24
@THIS                                                               // 25
D=M                                                                 // 26
@SP                                                                 // 27
A=M                                                                 // 28
M=D                                                                 // 29
@SP                                                                 // 30
M=M+1                                                               // 31
@THAT                                                               // 32
D=M                                                                 // 33
@SP                                                                 // 34
A=M                                                                 // 35
M=D                                                                 // 36
@SP                                                                 // 37
M=M+1                                                               // 38
@SP                                                                 // 39
D=M                                                                 // 40
@5                                                                  // 41
D=D-A                                                               // 42
@0                                                                  // 43
D=D-A                                                               // 44
@ARG                                                                // 45
M=D                                                                 // 46
@SP                                                                 // 47
D=M                                                                 // 48
@LCL                                                                // 49
M=D                                                                 // 50
@sys.init                                                           // 51
0;JMP                                                               // 52
(sys.init.return_0)
// function sys.init 0
(sys.init)
// push constant 6
@6                                                                  // 53
D=A                                                                 // 54
@SP                                                                 // 55
A=M                                                                 // 56
M=D                                                                 // 57
@SP                                                                 // 58
M=M+1                                                               // 59
// push constant 8
@8                                                                  // 60
D=A                                                                 // 61
@SP                                                                 // 62
A=M                                                                 // 63
M=D                                                                 // 64
@SP                                                                 // 65
M=M+1                                                               // 66
// call class1.set 2
@class1.set.return_1                                                // 67
D=A                                                                 // 68
@SP                                                                 // 69
A=M                                                                 // 70
M=D                                                                 // 71
@SP                                                                 // 72
M=M+1                                                               // 73
@LCL                                                                // 74
D=M                                                                 // 75
@SP                                                                 // 76
A=M                                                                 // 77
M=D                                                                 // 78
@SP                                                                 // 79
M=M+1                                                               // 80
@ARG                                                                // 81
D=M                                                                 // 82
@SP                                                                 // 83
A=M                                                                 // 84
M=D                                                                 // 85
@SP                                                                 // 86
M=M+1                                                               // 87
@THIS                                                               // 88
D=M                                                                 // 89
@SP                                                                 // 90
A=M                                                                 // 91
M=D                                                                 // 92
@SP                                                                 // 93
M=M+1                                                               // 94
@THAT                                                               // 95
D=M                                                                 // 96
@SP                                                                 // 97
A=M                                                                 // 98
M=D                                                                 // 99
@SP                                                                 // 100
M=M+1                                                               // 101
@SP                                                                 // 102
D=M                                                                 // 103
@5                                                                  // 104
D=D-A                                                               // 105
@2                                                                  // 106
D=D-A                                                               // 107
@ARG                                                                // 108
M=D                                                                 // 109
@SP                                                                 // 110
D=M                                                                 // 111
@LCL                                                                // 112
M=D                                                                 // 113
@class1.set                                                         // 114
0;JMP                                                               // 115
(class1.set.return_1)
// pop temp 0
@5                                                                  // 116
D=A                                                                 // 117
@R13                                                                // 118
M=D                                                                 // 119
@SP                                                                 // 120
M=M-1                                                               // 121
A=M                                                                 // 122
D=M                                                                 // 123
@R13                                                                // 124
A=M                                                                 // 125
M=D                                                                 // 126
// push constant 23
@23                                                                 // 127
D=A                                                                 // 128
@SP                                                                 // 129
A=M                                                                 // 130
M=D                                                                 // 131
@SP                                                                 // 132
M=M+1                                                               // 133
// push constant 15
@15                                                                 // 134
D=A                                                                 // 135
@SP                                                                 // 136
A=M                                                                 // 137
M=D                                                                 // 138
@SP                                                                 // 139
M=M+1                                                               // 140
// call class2.set 2
@class2.set.return_2                                                // 141
D=A                                                                 // 142
@SP                                                                 // 143
A=M                                                                 // 144
M=D                                                                 // 145
@SP                                                                 // 146
M=M+1                                                               // 147
@LCL                                                                // 148
D=M                                                                 // 149
@SP                                                                 // 150
A=M                                                                 // 151
M=D                                                                 // 152
@SP                                                                 // 153
M=M+1                                                               // 154
@ARG                                                                // 155
D=M                                                                 // 156
@SP                                                                 // 157
A=M                                                                 // 158
M=D                                                                 // 159
@SP                                                                 // 160
M=M+1                                                               // 161
@THIS                                                               // 162
D=M                                                                 // 163
@SP                                                                 // 164
A=M                                                                 // 165
M=D                                                                 // 166
@SP                                                                 // 167
M=M+1                                                               // 168
@THAT                                                               // 169
D=M                                                                 // 170
@SP                                                                 // 171
A=M                                                                 // 172
M=D                                                                 // 173
@SP                                                                 // 174
M=M+1                                                               // 175
@SP                                                                 // 176
D=M                                                                 // 177
@5                                                                  // 178
D=D-A                                                               // 179
@2                                                                  // 180
D=D-A                                                               // 181
@ARG                                                                // 182
M=D                                                                 // 183
@SP                                                                 // 184
D=M                                                                 // 185
@LCL                                                                // 186
M=D                                                                 // 187
@class2.set                                                         // 188
0;JMP                                                               // 189
(class2.set.return_2)
// pop temp 0
@5                                                                  // 190
D=A                                                                 // 191
@R13                                                                // 192
M=D                                                                 // 193
@SP                                                                 // 194
M=M-1                                                               // 195
A=M                                                                 // 196
D=M                                                                 // 197
@R13                                                                // 198
A=M                                                                 // 199
M=D                                                                 // 200
// call class1.get 0
@class1.get.return_3                                                // 201
D=A                                                                 // 202
@SP                                                                 // 203
A=M                                                                 // 204
M=D                                                                 // 205
@SP                                                                 // 206
M=M+1                                                               // 207
@LCL                                                                // 208
D=M                                                                 // 209
@SP                                                                 // 210
A=M                                                                 // 211
M=D                                                                 // 212
@SP                                                                 // 213
M=M+1                                                               // 214
@ARG                                                                // 215
D=M                                                                 // 216
@SP                                                                 // 217
A=M                                                                 // 218
M=D                                                                 // 219
@SP                                                                 // 220
M=M+1                                                               // 221
@THIS                                                               // 222
D=M                                                                 // 223
@SP                                                                 // 224
A=M                                                                 // 225
M=D                                                                 // 226
@SP                                                                 // 227
M=M+1                                                               // 228
@THAT                                                               // 229
D=M                                                                 // 230
@SP                                                                 // 231
A=M                                                                 // 232
M=D                                                                 // 233
@SP                                                                 // 234
M=M+1                                                               // 235
@SP                                                                 // 236
D=M                                                                 // 237
@5                                                                  // 238
D=D-A                                                               // 239
@0                                                                  // 240
D=D-A                                                               // 241
@ARG                                                                // 242
M=D                                                                 // 243
@SP                                                                 // 244
D=M                                                                 // 245
@LCL                                                                // 246
M=D                                                                 // 247
@class1.get                                                         // 248
0;JMP                                                               // 249
(class1.get.return_3)
// call class2.get 0
@class2.get.return_4                                                // 250
D=A                                                                 // 251
@SP                                                                 // 252
A=M                                                                 // 253
M=D                                                                 // 254
@SP                                                                 // 255
M=M+1                                                               // 256
@LCL                                                                // 257
D=M                                                                 // 258
@SP                                                                 // 259
A=M                                                                 // 260
M=D                                                                 // 261
@SP                                                                 // 262
M=M+1                                                               // 263
@ARG                                                                // 264
D=M                                                                 // 265
@SP                                                                 // 266
A=M                                                                 // 267
M=D                                                                 // 268
@SP                                                                 // 269
M=M+1                                                               // 270
@THIS                                                               // 271
D=M                                                                 // 272
@SP                                                                 // 273
A=M                                                                 // 274
M=D                                                                 // 275
@SP                                                                 // 276
M=M+1                                                               // 277
@THAT                                                               // 278
D=M                                                                 // 279
@SP                                                                 // 280
A=M                                                                 // 281
M=D                                                                 // 282
@SP                                                                 // 283
M=M+1                                                               // 284
@SP                                                                 // 285
D=M                                                                 // 286
@5                                                                  // 287
D=D-A                                                               // 288
@0                                                                  // 289
D=D-A                                                               // 290
@ARG                                                                // 291
M=D                                                                 // 292
@SP                                                                 // 293
D=M                                                                 // 294
@LCL                                                                // 295
M=D                                                                 // 296
@class2.get                                                         // 297
0;JMP                                                               // 298
(class2.get.return_4)
// label while
(while)
// goto while
@while                                                              // 299
0;JMP                                                               // 300
// function class2.set 0
(class2.set)
// push argument 0
@0                                                                  // 301
D=A                                                                 // 302
@ARG                                                                // 303
A=D+M                                                               // 304
D=M                                                                 // 305
@SP                                                                 // 306
A=M                                                                 // 307
M=D                                                                 // 308
@SP                                                                 // 309
M=M+1                                                               // 310
// pop static 0
@16                                                                 // 311
D=A                                                                 // 312
@R13                                                                // 313
M=D                                                                 // 314
@SP                                                                 // 315
M=M-1                                                               // 316
A=M                                                                 // 317
D=M                                                                 // 318
@R13                                                                // 319
A=M                                                                 // 320
M=D                                                                 // 321
// push argument 1
@1                                                                  // 322
D=A                                                                 // 323
@ARG                                                                // 324
A=D+M                                                               // 325
D=M                                                                 // 326
@SP                                                                 // 327
A=M                                                                 // 328
M=D                                                                 // 329
@SP                                                                 // 330
M=M+1                                                               // 331
// pop static 1
@17                                                                 // 332
D=A                                                                 // 333
@R13                                                                // 334
M=D                                                                 // 335
@SP                                                                 // 336
M=M-1                                                               // 337
A=M                                                                 // 338
D=M                                                                 // 339
@R13                                                                // 340
A=M                                                                 // 341
M=D                                                                 // 342
// push constant 0
@0                                                                  // 343
D=A                                                                 // 344
@SP                                                                 // 345
A=M                                                                 // 346
M=D                                                                 // 347
@SP                                                                 // 348
M=M+1                                                               // 349
// return
@5                                                                  // 350
D=A                                                                 // 351
@LCL                                                                // 352
D=M-D                                                               // 353
A=D                                                                 // 354
D=M                                                                 // 355
@R14                                                                // 356
M=D                                                                 // 357
@0                                                                  // 358
D=A                                                                 // 359
@ARG                                                                // 360
A=D+M                                                               // 361
D=A                                                                 // 362
@R13                                                                // 363
M=D                                                                 // 364
@SP                                                                 // 365
M=M-1                                                               // 366
A=M                                                                 // 367
D=M                                                                 // 368
@R13                                                                // 369
A=M                                                                 // 370
M=D                                                                 // 371
@ARG                                                                // 372
D=M+1                                                               // 373
@SP                                                                 // 374
M=D                                                                 // 375
@LCL                                                                // 376
M=M-1                                                               // 377
@LCL                                                                // 378
A=M                                                                 // 379
D=M                                                                 // 380
@THAT                                                               // 381
M=D                                                                 // 382
@LCL                                                                // 383
M=M-1                                                               // 384
@LCL                                                                // 385
A=M                                                                 // 386
D=M                                                                 // 387
@THIS                                                               // 388
M=D                                                                 // 389
@LCL                                                                // 390
M=M-1                                                               // 391
@LCL                                                                // 392
A=M                                                                 // 393
D=M                                                                 // 394
@ARG                                                                // 395
M=D                                                                 // 396
@LCL                                                                // 397
M=M-1                                                               // 398
@LCL                                                                // 399
A=M                                                                 // 400
D=M                                                                 // 401
@LCL                                                                // 402
M=D                                                                 // 403
@R14                                                                // 404
A=M                                                                 // 405
0;JMP                                                               // 406
// function class2.get 0
(class2.get)
// push static 0
@16                                                                 // 407
D=M                                                                 // 408
@SP                                                                 // 409
A=M                                                                 // 410
M=D                                                                 // 411
@SP                                                                 // 412
M=M+1                                                               // 413
// push static 1
@17                                                                 // 414
D=M                                                                 // 415
@SP                                                                 // 416
A=M                                                                 // 417
M=D                                                                 // 418
@SP                                                                 // 419
M=M+1                                                               // 420
// sub
@SP                                                                 // 421
M=M-1                                                               // 422
@SP                                                                 // 423
A=M                                                                 // 424
D=M                                                                 // 425
@SP                                                                 // 426
M=M-1                                                               // 427
@SP                                                                 // 428
A=M                                                                 // 429
M=M-D                                                               // 430
@SP                                                                 // 431
M=M+1                                                               // 432
// return
@5                                                                  // 433
D=A                                                                 // 434
@LCL                                                                // 435
D=M-D                                                               // 436
A=D                                                                 // 437
D=M                                                                 // 438
@R14                                                                // 439
M=D                                                                 // 440
@0                                                                  // 441
D=A                                                                 // 442
@ARG                                                                // 443
A=D+M                                                               // 444
D=A                                                                 // 445
@R13                                                                // 446
M=D                                                                 // 447
@SP                                                                 // 448
M=M-1                                                               // 449
A=M                                                                 // 450
D=M                                                                 // 451
@R13                                                                // 452
A=M                                                                 // 453
M=D                                                                 // 454
@ARG                                                                // 455
D=M+1                                                               // 456
@SP                                                                 // 457
M=D                                                                 // 458
@LCL                                                                // 459
M=M-1                                                               // 460
@LCL                                                                // 461
A=M                                                                 // 462
D=M                                                                 // 463
@THAT                                                               // 464
M=D                                                                 // 465
@LCL                                                                // 466
M=M-1                                                               // 467
@LCL                                                                // 468
A=M                                                                 // 469
D=M                                                                 // 470
@THIS                                                               // 471
M=D                                                                 // 472
@LCL                                                                // 473
M=M-1                                                               // 474
@LCL                                                                // 475
A=M                                                                 // 476
D=M                                                                 // 477
@ARG                                                                // 478
M=D                                                                 // 479
@LCL                                                                // 480
M=M-1                                                               // 481
@LCL                                                                // 482
A=M                                                                 // 483
D=M                                                                 // 484
@LCL                                                                // 485
M=D                                                                 // 486
@R14                                                                // 487
A=M                                                                 // 488
0;JMP                                                               // 489
// function class1.set 0
(class1.set)
// push argument 0
@0                                                                  // 490
D=A                                                                 // 491
@ARG                                                                // 492
A=D+M                                                               // 493
D=M                                                                 // 494
@SP                                                                 // 495
A=M                                                                 // 496
M=D                                                                 // 497
@SP                                                                 // 498
M=M+1                                                               // 499
// pop static 0
@18                                                                 // 500
D=A                                                                 // 501
@R13                                                                // 502
M=D                                                                 // 503
@SP                                                                 // 504
M=M-1                                                               // 505
A=M                                                                 // 506
D=M                                                                 // 507
@R13                                                                // 508
A=M                                                                 // 509
M=D                                                                 // 510
// push argument 1
@1                                                                  // 511
D=A                                                                 // 512
@ARG                                                                // 513
A=D+M                                                               // 514
D=M                                                                 // 515
@SP                                                                 // 516
A=M                                                                 // 517
M=D                                                                 // 518
@SP                                                                 // 519
M=M+1                                                               // 520
// pop static 1
@19                                                                 // 521
D=A                                                                 // 522
@R13                                                                // 523
M=D                                                                 // 524
@SP                                                                 // 525
M=M-1                                                               // 526
A=M                                                                 // 527
D=M                                                                 // 528
@R13                                                                // 529
A=M                                                                 // 530
M=D                                                                 // 531
// push constant 0
@0                                                                  // 532
D=A                                                                 // 533
@SP                                                                 // 534
A=M                                                                 // 535
M=D                                                                 // 536
@SP                                                                 // 537
M=M+1                                                               // 538
// return
@5                                                                  // 539
D=A                                                                 // 540
@LCL                                                                // 541
D=M-D                                                               // 542
A=D                                                                 // 543
D=M                                                                 // 544
@R14                                                                // 545
M=D                                                                 // 546
@0                                                                  // 547
D=A                                                                 // 548
@ARG                                                                // 549
A=D+M                                                               // 550
D=A                                                                 // 551
@R13                                                                // 552
M=D                                                                 // 553
@SP                                                                 // 554
M=M-1                                                               // 555
A=M                                                                 // 556
D=M                                                                 // 557
@R13                                                                // 558
A=M                                                                 // 559
M=D                                                                 // 560
@ARG                                                                // 561
D=M+1                                                               // 562
@SP                                                                 // 563
M=D                                                                 // 564
@LCL                                                                // 565
M=M-1                                                               // 566
@LCL                                                                // 567
A=M                                                                 // 568
D=M                                                                 // 569
@THAT                                                               // 570
M=D                                                                 // 571
@LCL                                                                // 572
M=M-1                                                               // 573
@LCL                                                                // 574
A=M                                                                 // 575
D=M                                                                 // 576
@THIS                                                               // 577
M=D                                                                 // 578
@LCL                                                                // 579
M=M-1                                                               // 580
@LCL                                                                // 581
A=M                                                                 // 582
D=M                                                                 // 583
@ARG                                                                // 584
M=D                                                                 // 585
@LCL                                                                // 586
M=M-1                                                               // 587
@LCL                                                                // 588
A=M                                                                 // 589
D=M                                                                 // 590
@LCL                                                                // 591
M=D                                                                 // 592
@R14                                                                // 593
A=M                                                                 // 594
0;JMP                                                               // 595
// function class1.get 0
(class1.get)
// push static 0
@18                                                                 // 596
D=M                                                                 // 597
@SP                                                                 // 598
A=M                                                                 // 599
M=D                                                                 // 600
@SP                                                                 // 601
M=M+1                                                               // 602
// push static 1
@19                                                                 // 603
D=M                                                                 // 604
@SP                                                                 // 605
A=M                                                                 // 606
M=D                                                                 // 607
@SP                                                                 // 608
M=M+1                                                               // 609
// sub
@SP                                                                 // 610
M=M-1                                                               // 611
@SP                                                                 // 612
A=M                                                                 // 613
D=M                                                                 // 614
@SP                                                                 // 615
M=M-1                                                               // 616
@SP                                                                 // 617
A=M                                                                 // 618
M=M-D                                                               // 619
@SP                                                                 // 620
M=M+1                                                               // 621
// return
@5                                                                  // 622
D=A                                                                 // 623
@LCL                                                                // 624
D=M-D                                                               // 625
A=D                                                                 // 626
D=M                                                                 // 627
@R14                                                                // 628
M=D                                                                 // 629
@0                                                                  // 630
D=A                                                                 // 631
@ARG                                                                // 632
A=D+M                                                               // 633
D=A                                                                 // 634
@R13                                                                // 635
M=D                                                                 // 636
@SP                                                                 // 637
M=M-1                                                               // 638
A=M                                                                 // 639
D=M                                                                 // 640
@R13                                                                // 641
A=M                                                                 // 642
M=D                                                                 // 643
@ARG                                                                // 644
D=M+1                                                               // 645
@SP                                                                 // 646
M=D                                                                 // 647
@LCL                                                                // 648
M=M-1                                                               // 649
@LCL                                                                // 650
A=M                                                                 // 651
D=M                                                                 // 652
@THAT                                                               // 653
M=D                                                                 // 654
@LCL                                                                // 655
M=M-1                                                               // 656
@LCL                                                                // 657
A=M                                                                 // 658
D=M                                                                 // 659
@THIS                                                               // 660
M=D                                                                 // 661
@LCL                                                                // 662
M=M-1                                                               // 663
@LCL                                                                // 664
A=M                                                                 // 665
D=M                                                                 // 666
@ARG                                                                // 667
M=D                                                                 // 668
@LCL                                                                // 669
M=M-1                                                               // 670
@LCL                                                                // 671
A=M                                                                 // 672
D=M                                                                 // 673
@LCL                                                                // 674
M=D                                                                 // 675
@R14                                                                // 676
A=M                                                                 // 677
0;JMP                                                               // 678
